/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary-container": "#715d00",
              "surface-variant": "#2e3637",
              "outline-variant": "#3b494b",
              "outline": "#849495",
              "on-secondary-fixed": "#002022",
              "error-container": "#93000a",
              "surface": "#0d1515",
              "inverse-on-surface": "#2a3233",
              "surface-container-low": "#151d1e",
              "on-background": "#dce4e5",
              "primary-fixed": "#7df4ff",
              "on-secondary-container": "#84bfc5",
              "on-primary-container": "#006970",
              "on-error-container": "#ffdad6",
              "surface-container-high": "#232b2c",
              "error": "#ffb4ab",
              "on-tertiary-fixed-variant": "#554500",
              "tertiary": "#fff5de",
              "on-tertiary": "#3b2f00",
              "surface-container-lowest": "#080f10",
              "tertiary-container": "#fed639",
              "surface-dim": "#0d1515",
              "secondary": "#96d1d6",
              "tertiary-fixed": "#ffe179",
              "secondary-fixed": "#b1edf3",
              "primary-container": "#00f0ff",
              "on-primary-fixed-variant": "#004f54",
              "on-primary-fixed": "#002022",
              "tertiary-fixed-dim": "#eac324",
              "on-surface-variant": "#b9cacb",
              "secondary-container": "#074f54",
              "on-secondary": "#00363a",
              "on-primary": "#00363a",
              "primary-fixed-dim": "#00dbe9",
              "on-secondary-fixed-variant": "#074f54",
              "inverse-primary": "#006970",
              "surface-tint": "#00dbe9",
              "on-surface": "#dce4e5",
              "surface-container-highest": "#2e3637",
              "secondary-fixed-dim": "#96d1d6",
              "background": "#0d1515",
              "inverse-surface": "#dce4e5",
              "surface-bright": "#333b3b",
              "on-error": "#690005",
              "surface-container": "#192122",
              "primary": "#dbfcff",
              "on-tertiary-fixed": "#231b00"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Space Grotesk"],
              "display": ["Space Grotesk"],
              "body": ["Inter"],
              "label": ["Public Sans"]
      }
    },
  },
  plugins: [],
}
