from sentence_transformers import SentenceTransformer, util
import numpy as np

# Load the sentence transformer model lazily to avoid startup hang
_model = None

def get_model():
    global _model
    if _model is None:
        try:
            print("Loading evaluation model (this may take a moment on first run)...")
            _model = SentenceTransformer('all-MiniLM-L6-v2')
        except Exception as e:
            print(f"Error loading sentence transformer model: {e}")
    return _model

# A mock database of expected answers or key concepts for our generated questions
# In a real app, this could be generated by an LLM or stored in a DB
EXPECTED_ANSWERS_DB = {
    # React questions
    "What are React Hooks? Can you name some common ones?": "React Hooks are functions that let you use state and lifecycle features in functional components. Common ones include useState, useEffect, useContext, and useReducer.",
    "Explain the virtual DOM and its benefits.": "The virtual DOM is a lightweight copy of the actual DOM. React uses it to batch updates and calculate the minimum number of changes needed before updating the real DOM, which improves performance.",
    "How do you manage state in a complex React application?": "State in complex React apps can be managed using Context API for global state, or external libraries like Redux, MobX, or Zustand to handle complex state logic and avoid prop drilling.",
    "What is the difference between functional and class components?": "Functional components are simpler, use functions, and rely on hooks for state and lifecycle. Class components use ES6 classes, have a render method, and use an explicit state object and lifecycle methods.",
    
    # Python questions
    "What are decorators, and how are they used?": "Decorators in Python are functions that modify the behavior of another function or class. They are applied using the @ symbol above the definition and are commonly used for logging, access control, or caching.",
    "What are the differences between lists and tuples in Python?": "Lists are mutable, meaning they can be changed after creation, and are defined with square brackets. Tuples are immutable and defined with parentheses, generally making them faster and safer for fixed data.",
    "How does memory management work in Python?": "Python uses a private heap containing all objects and data structures. Memory management is handled automatically using reference counting and a garbage collector to handle cyclic references.",
    "Explain the context manager and the 'with' statement in Python.": "Context managers allocate and release resources exactly when needed. The 'with' statement simplifies exception handling by encapsulating common preparation and cleanup tasks, particularly for file operations.",
    
    # Machine Learning questions
    "Describe a precision vs. recall tradeoff in a classification model.": "Precision measures the accuracy of positive predictions (minimizing false positives), while recall measures the ability to find all positive instances (minimizing false negatives). Improving one often comes at the cost of the other.",
    "Can you explain the difference between supervised and unsupervised learning?": "Supervised learning uses labeled data to train models to predict outcomes, whereas unsupervised learning looks for patterns in unlabeled data, like grouping or clustering.",
    "What is overfitting, and how do you prevent it?": "Overfitting happens when a model learns the training data too well, including its noise, leading to poor generalization. It can be prevented using techniques like cross-validation, regularization, dropout, or early stopping.",
    "Explain the concept of cross-validation.": "Cross-validation is a resampling procedure used to evaluate models on a limited data sample. It splits the data into k folds, training on k-1 folds and testing on the remaining one, rotating iteratively.",
    
    # Docker questions
    "Explain the difference between a Docker image and a Docker container.": "A Docker image is a read-only template that contains the application and its environment. A container is a runnable, isolated instance of that image.",
    "What are the main advantages of using Docker for deployment?": "Docker ensures consistency across environments (development to production), isolates applications, simplifies dependency management, and allows for rapid scaling and lightweight deployment.",
    "How do you network multiple containers together using Docker Compose?": "Docker Compose allows you to define multi-container applications in a YAML file. It automatically creates a default network where containers can discover and communicate with each other using their service names.",
    
    # General HR questions
    "Why are you interested in this position?": "I am interested in this position because the role aligns with my career goals, allows me to leverage my skills in a challenging environment, and I am excited about the company's mission and product.",
    "Tell me about a time you faced a challenging technical problem and how you resolved it.": "I encountered a challenging bug where performance was degrading. I resolved it by profiling the code, identifying a quadratic complexity loop, and refactoring it to use a hash map, reducing the time complexity significantly.",
    "Where do you see yourself in 5 years?": "In 5 years, I aim to have deepened my technical expertise, taken on leadership responsibilities, and contributed to architecting robust solutions that drive business value.",
    "Describe your experience working in a team environment.": "I have experience working agile environments, participating in code reviews, daily stand-ups, and collaborative problem solving. I value clear communication and mentoring team members."
}

def evaluate_answer(question: str, answer: str) -> dict:
    """
    Evaluates the quality of an answer to a given question using sentence embeddings.
    
    Args:
        question (str): The interview question.
        answer (str): The candidate's answer.
        
    Returns:
        dict: A dictionary containing the score (0-100) and feedback.
    """
    model = get_model()
    if not model:
        return {
            "score": 0,
            "feedback": "Internal error: Evaluation model not loaded."
        }
        
    if not answer or len(answer.strip()) < 5:
        return {
            "score": 0,
            "feedback": "Your answer is too short to evaluate."
        }

    # Retrieve expected answer or fallback to a basic keyword check if question not found
    expected_answer = EXPECTED_ANSWERS_DB.get(question)
    
    if not expected_answer:
        # Fallback: if we don't have an expected answer, use the question as the semantic core.
        # In a more advanced version, we could use an LLM here.
        expected_answer = question
    
    # Compute embeddings
    model = get_model()
    embeddings_expected = model.encode(expected_answer, convert_to_tensor=True)
    embeddings_candidate = model.encode(answer, convert_to_tensor=True)
    
    # Compute cosine similarity
    cosine_score = util.cos_sim(embeddings_expected, embeddings_candidate)
    
    # Extract the score as a float and convert to a 0-100 scale
    similarity_val = float(cosine_score[0][0])
    
    # Map score to a 0-100 range and cap it
    score_out_of_100 = max(0, min(100, int(similarity_val * 100)))
    
    # Generate feedback based on thresholds
    if score_out_of_100 >= 80:
        feedback = "Excellent answer! You covered the key concepts well."
    elif score_out_of_100 >= 60:
        feedback = "Good answer, but it could be more detailed. Consider incorporating more specific technical terms or examples."
    elif score_out_of_100 >= 40:
        feedback = "Fair attempt. Your answer is somewhat related but misses some core concepts."
    else:
        feedback = "Your answer doesn't seem to address the question accurately. Please review the core concepts of this topic."
        
    return {
        "score": score_out_of_100,
        "feedback": feedback
    }
